image: leanprovercommunity/mathlib:gitpod

vscode:
  extensions:
    - jroesch.lean

tasks:
  - init: pip install -r requirements.txt
  - command: . /home/gitpod/.profile && leanpkg configure && leanproject get-mathlib-cache
